name: CI Workflow

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set up Python 3.8+
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Norminette
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install norminette

      - name: Run Norminette
        run: |
          # Run Norminette on all .c and .h files in the repository
          norminette $(find . -type f -name "*.c" -or -name "*.h")
      
      - name: Run Makefile Build
        run: |
          make all 

      - name: Run Unit Tests
        run: |
          python3 path/to/your/test_script.py
        run: make test

      - name: Clean files
        run: |
          make fclean
